title: Pepe b coode
description: > # this means to ignore newlines until "baseurl:"
  Rants on programming, and computer science in general
url: "http://pepegar.github.io" # the base hostname & protocol for your site
twitter_username: jlgarhdez
github_username:  pepegar
permalink: /:year/:month/:title.html
excerpt_separator: "\n\n"
# Build settings
markdown: kramdown
theme: minima
